### ISSUE TITLE
Unable to wake anything

### ISSUE THREAD

**Issue by grandiego** [OpenMediaVault-Plugin-Developers/openmediavault-wol#1]
I've just scanned my home network, and successfully discovered all my computers.
If I select any of them and click on "send" button, nothing happens.
But if I send a WoL packet from Android app "Wake on Lan", or from CLI using wakeonlan instead on etherwake, I can wake any computer on my network.
I'm using openmediavault-wol 1.0.2, btw

Thanks in advance

**Comment by wyild1** [comment]
I am having the same issue.  Can issue a wakeonlan MAC from CLI but nothing from the GUI.  OMV 1.1, omv-wol 1.0.2

**Comment by ryecoaaron** [comment]
What command are you using?

**Comment by wyild1** [comment]
From the command line I used "wakeonlan 50:E5:49:CE:5C:72" and it wakes up the computer im trying to wake up.  But from the GUI, nothing happens

**Comment by wyild1** [comment]
Looks like I can issue "sudo etherwake 50:E5:49:CE:5C:72 -i eth0" from the CLI and it wakes up the machine as well

**Comment by ryecoaaron** [comment]
Try 1.0.3 in the repo now.  Had a stupid typo that would never allow it to work.

**Comment by wyild1** [comment]
It works now!  Thank you for your quick response!!!

**Comment by grandiego** [comment]
I've tried it, but still doesn't work

**Comment by ryecoaaron** [comment]
Does it work from the command line?  Try wyild1's etherwake command from above.

**Comment by grandiego** [comment]
I've tried it (obviuosly changing MAC address), but nothing happens. No errors, no output, but no wake up.
Using wakeonlan instead of etherwake works flawlessly

**Comment by ryecoaaron** [comment]
Try 1.0.4 in repo now.  It uses both etherwake and wakeonlan.

**Comment by grandiego** [comment]
Works perfect now!

Thank you so much.
