### ISSUE TITLE
openmediavault-wol tries to use eth0 even if non-existent

### ISSUE THREAD

**Issue by petaramesh** [OpenMediaVault-Plugin-Developers/openmediavault-wol#2]
Hi,

I have installed OMV WOL plugin :

Package: openmediavault-wol
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 169
Maintainer: OpenMediaVault Plugin Developers <plugins@omv-extras.org>
Architecture: all
Version: 3.2

Trying to send a WOL packet on my LAN causes an error message stating that eth0 is not available.

And actually, my NAS 1st ethernet interfaces are named eno1 and eno2

/usr/share/openmediavault/engined/rpc/wol.inc line 158 calls "etherwake" without specifying the ethernet interface to use, and etherwake defaults to eth0.

It would be advisable to make the interface to use parametrable, as to send "etherwake -i eno1 <MACaddr»".

Or rather to use "wakeonlan" instead of "etherwake", as wakeonlan determines the interface by itself.

It should be enough to replace "etherwake" with "wakeonlan" in /usr/share/openmediavault/engined/rpc/wol.inc line 158 (and update package dependacy accordingly)

**Comment by ryecoaaron** [comment]
The plugin already installs wakeonlan.  I look at a couple of things to fix this.

**Comment by ryecoaaron** [comment]
Did you look at line 163?  It uses wakeonlan when it has a mac address.  There are still a few things I can do to improve the code though.

**Comment by petaramesh** [comment]
Hello,
The version installed on my NAS from OMV extras is 3.2, line 163 has nothing to do with wakeonlan, and the work "wakeonlan" cannot be grepped anywhere in /var/www/openmediavault/js/omv/module/admin/service/wol/*

**Comment by ryecoaaron** [comment]
Uh, 3.2 is the current version and I added the wakeonlan code about a year and half ago - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wol/commit/8a294304b750d9f916439b3dec7ffd5eeb67f42e

Your grep is checking the wrong directory.  That is the javascript directory for the web interface.  Try this grep:  grep -i wakeonlan /usr/share/openmediavault/engined/rpc/wol.inc

**Comment by petaramesh** [comment]
You're right, I can see wakeonlan in this grep.

But then, how comes that, when trying to wak a computer which MAC I have provided, I get :

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; etherwake 00:26:18:CE:6A:1A 2>&1' with exit code '1': SIOCGIFHWADDR on eth0 failed: No such device

Erreur #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; etherwake 00:26:18:CE:6A:1A 2>&1' with exit code '1': SIOCGIFHWADDR on eth0 failed: No such device in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/wol.inc(160): OMV\System\Process->execute()
#1 [internal function]: OMVRpcServiceWol->doSend(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doSend', Array, Array)
#4 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Wol', 'doSend', Array, Array, 1)
#5 {main}

**Comment by ryecoaaron** [comment]
I still need to fix etherwake to use the right network adapter.  That is why I didn't close this issue yet.  I was just letting you know the wakeonlan stuff was already there.

**Comment by ryecoaaron** [comment]
Should be fixed in 3.3 in the repos now.

**Comment by petaramesh** [comment]
Hello,
I just installed 3.3, but unfortunately...

: Missing 'required' attribute 'deviceName'.
Erreur #0:
OMV\Json\SchemaValidationException: : Missing 'required' attribute 'deviceName'. in /usr/share/php/openmediavault/json/schema.inc:618
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(395): OMV\Json\Schema->checkProperties(Object(stdClass), Array, '')
#1 /usr/share/php/openmediavault/json/schema.inc(285): OMV\Json\Schema->validateObject(Object(stdClass), Array, '')
#2 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(Object(stdClass), Array, '')
#3 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate(Object(stdClass))
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(170): OMV\Rpc\ParamsValidator->validate('{"uuid":"e8d362...')
#5 /usr/share/openmediavault/engined/rpc/wol.inc(140): OMV\Rpc\ServiceAbstract->validateMethodParams(Array, 'rpc.wol.send')
#6 [internal function]: OMVRpcServiceWol->doSend(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doSend', Array, Array)
#9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Wol', 'doSend', Array, Array, 1)
#10 {main}

**Comment by ryecoaaron** [comment]
Do you see the device dropdown next to the send button?  If, not, clear your browser cache.

**Comment by petaramesh** [comment]
I hadn't noticed the new interface box. Now it works, thank you :-)
