### ISSUE TITLE
Automatic selection of nic when there is only one

### ISSUE THREAD

**Issue by grandiego** [OpenMediaVault-Plugin-Developers/openmediavault-wol#3]
I've noted that now there's a drop down selection box to choose the network card used to send WOL packets.
It would be nice to have 'eth0' selected by default, at least when there is just one network card in the system.

**Comment by ryecoaaron** [comment]
There are a couple of problems with that.  The default value is just a text field.  So, it can't really do any logic to determine if there is one network card.  And not everyone's network card is named eth0.

I guess I could make it optional but then it would have to use wakeonlan only (and not etherwake).

**Comment by grandiego** [comment]
No problem.
