### ISSUE TITLE
Scan feature doesn't work for bonded cards

### ISSUE THREAD

**Issue by helshabini** [OpenMediaVault-Plugin-Developers/openmediavault-wol#4]
Using OMV on a server with bonded cards. The resulting interface is labeled (bond0).
It seems **nast** is always trying to pick up the first interface (enp3s0). Resulting in the following error:

`Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; nast -m' with exit code '255': 
[1mNast V. 0.2.0[0m
 in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/wol.inc(173): OMV\System\Process->execute(Array)
#1 [internal function]: OMVRpcServiceWol->doScan(NULL, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doScan', NULL, Array)
#4 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Wol', 'doScan', NULL, Array, 1)
#5 {main}`

A quick fix is to modify wol.inc to include the -i switch for nast RPC call. If you allow me to fork the repo I can probably do it.

**Comment by ryecoaaron** [comment]
Fixed in 3.4.  The interface is optional. If specified, it will append the -i parameter with the interface name.

Just a note, you are always allowed to fork a repo and submit pull requests.
