### ISSUE TITLE
OMV5 & nast V0.2.0 => incorrect SCAN result processing => a quick fix supplied

### ISSUE THREAD

**Issue by vermeerpaul** [OpenMediaVault-Plugin-Developers/openmediavault-wol#5]
cmd `nast -m` returns its line for localhost slightly different than other hosts on the network. This is actually an issue to be addressed in Linux code base for nast to tidy up its formatting.

Localhost (127.0.0.1) separates its line / string for MAC and IP address with a \t, whereas other hosts have a space and \t as separator. Using the function explode as a split on space therefore fails for that entry and goes unnoticed because of the extra (*) field. Though it won't be an issue as sending out a WOL to itself is pretty much a rhetoric call anyways, but it does mess-up the table content in the xml file. Subsequently, using those recorded MAC address values elsewhere in code becomes problematic, hence this suggestion for improvement / change.

Also the name needs to be unique - using generic value 'n/a' does not guarantee it being unique.

Replace line 184 
FROM
  `$pieces = explode(' ', str_replace('(', '', str_replace(')', '', $line)));`
TO
  `$line = str_replace('(', '', str_replace(')', '', $line));
   $pieces = preg_split('/\s+/', $line);`

AND to make each line unique in case there's no name provided - create a (better) unique name:
Replace line 187
FROM
  `$pieces[2] = gettext("n/a");`
TO
  `$pieces[2] = gettext("n/a - " . trim($pieces[1]));`

Another linked problem .... running SCAN twice in a row, without deleting the records results in an error - because each entry that was there will be in conflict with the newly provided (same) results. Code function setSystem(x,y) dictates that each entry needs to be unique though. A simple work-around: manually select all entries and delete before applying a (re-)scan.

**Comment by ryecoaaron** [comment]
5.x is EOL and the name no longer has to be unique in the 6.x plugin.
