### ISSUE TITLE
openmediavault-WOL - 500 - Internal Server Error

### ISSUE THREAD

**Issue by filipeaguiars** [OpenMediaVault-Plugin-Developers/openmediavault-wol#6]
Hello, Everyone :D

Can I have some help?

I'm trying to set up WOL on my machine, but I'm getting this error when setting RTCWake.

500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; rtcwake -a -t 1659931200 -m mem' with exit code '1':

![image_2022-08-08_102830402](https://user-images.githubusercontent.com/17336136/183429267-f3319e31-43ec-4c05-bd14-371245a48294.png)

This error appears after pressing the "Set" button.

Thanks in advance :D

**Comment by filipeaguiars** [comment]
I tried running the command on the red box and got the following message:

> rtcwake: time doesn't go backward to Mon Aug  8 04:00:00 2022

the command is: 

> export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; rtcwake -a -t 1659931200 -m mem

![image](https://user-images.githubusercontent.com/17336136/183440382-ccc6d13b-b743-4eab-a81d-1a3d462460db.png)

**Comment by ryecoaaron** [comment]
You don't need to post in both places. I see it on the forum too.  I just chose to respond on the forum because it is easier.

**Comment by seabstisnaaldsf** [comment]
what was the problem? I have the same issue

**Comment by seabstisnaaldsf** [comment]
500 - Internal Server Error Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-mkraid /dev/md0 -l raid6 -n 5 /dev/sda /dev/sdb /dev/sdd /dev/sde /dev/sdf 2>&1' with exit code '1': mdadm: layout defaults to left-symmetric mdadm: layout defaults to left-symmetric mdadm: chunk size defaults to 512K mdadm: super1.x cannot open /dev/sdf: Device or resource busy mdadm: /dev/sdf is not suitable for this array. mdadm: create aborted

that's my error code... I don't know what's the problem..

**Comment by ryecoaaron** [comment]
Your error is referring to raid not the WOL plugin.  Why do you think it is the WOL plugin?  I would post on the forum.
